### ISSUE TITLE
Server Crash

### ISSUE THREAD

**Issue by Bogdan-G** [Qmunity/QmunityLib#5] opened 2015-02-15 12:16 UTC
MC 1.7.10
Forge 1240
CCC 1.0.4.35(last ver), BluePower 0.2.857, QmunityLib 0.1.78/76, 
ForgeMultipart 1.1.1.322, CodeChickenLib 1.1.3.127 (last)
Server crash in load world (QmunityLib 0.1.78): http://pastebin.com/DuuCkkXD
Server crash in load world (QmunityLib 0.1.76): http://pastebin.com/jx6mrzWS

**Comment by Quetzi** [comment] 2015-02-15 13:22
Hey, This is a duplicate of #2 and #3 and is fixed as of build .79 which I realise hasn't yet been released (We're doing a batch of final testing, it's is imminent) For now build 69 should work fine.

**Closed by Quetzi** 2015-02-15 13:22 UTC
